- hosts: localhost
  tasks:
    - name: Ansible init
      debug:
        msg: Hello Ansible World
    - name: Installing Rsync
      apt: >
        pkg={{ item }}
        state=latest
        update_cache=yes
        cache_valid_time=3600
      with_items:
      - rsync
    - name: upload the site directory to the docker host
      synchronize: src=workshopapp dest=/tmp
      register: sync_result
    # - name: Build Docker image
    #   command: docker build -t demo:latest /tmp/workshopapp