name: Deploy DEV

on:
  push:
    branches: [ develop ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/ansible
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}