name: Deploy DEV

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: build.yml
          directory: ../playbooks/
          options: |
            --verbose