name: Deploy DEV

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ansible 
        uses: tomasnorre/ansible-cli-action@0.0.5
        with:
          command: ansible-playbook palaybooks/build.yml