name: Deploy DEV

on:
  push:
    branches: [ develop ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  build:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          settings-path: ${{ github.workspace }}
      - name: Ansible build Docker image
        uses: Hugozys/ansible-deploy@master
        with:
          directory: './playbooks/'
          playbook: 'build.yaml'