name: Deploy DEV

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ansible build Docker image
        uses: tomasnorre/ansible-cli-action@0.0.5
        command: ansible-playbook palaybooks/build.yml