name: Pull request actions

on:
  pull_request:
    branches: [ develop,master ]
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |

            var msg = `👋 👋 👋 Label for automate pull request merge 👋 👋 👋 
            var body = context.payload.pull_request.body

            # Create comment
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })

            # Add label
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['new submission']
            })


  initial:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ github.run_number }}

  test:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
         settings-path: ${{ github.workspace }}
     - name: Test with Maven
       run: mvn -Dmaven.test.failure.ignore=true test
     - name: Report
       uses: dorny/test-reporter@v1
       if: always()
       with:
         name: Maven Tests
         path: target/surefire-reports/*.xml
         reporter: java-junit
         fail-on-error: true
