name: Open pull request actions

on:
  pull_request:
    types: [opened,reopened]

jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge with Develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: ${{ github.event.pull_request.head.ref }}
          github_token: ${{ github.token }}

  test:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
         settings-path: ${{ github.workspace }}
     - name: Test with Maven
       run: mvn -Dmaven.test.failure.ignore=true test
     - name: Report
       uses: dorny/test-reporter@v1
       if: always()
       with:
         name: Maven Tests
         path: target/surefire-reports/*.xml
         reporter: java-junit
         fail-on-error: true
