name: Deploy DEV

on:
  pull_request:
    types: [merged]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml
    - name: Save build
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/target/*.jar
        retention-days: 1
    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
  deploy:
    runs-on: ubuntu-18.04
    needs: build

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
          name: jar-artifact
          path: target/
    - name: Docker build
      run: |
        docker build . -t devs90/workshop:8
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker push
      run: |
        docker push devs90/workshop:8
